In [ ]:
# !pip install imgaug
# !pip uninstall opencv-python
# !pip install opencv-python-headless

In [ ]:

import imageio
import imgaug as ia
from imgaug import augmenters as iaa
import numpy as np

# Open the image form working directory
# image = imageio.imread("/root/fish_fillet_image_program_ML/fish/temp/data/image/cl8i0kllo6e8m070e4c4sbr6w_0.jpg")
image = imageio.imread("/root/fish_fillet_image_program_ML/fish/temp/data/mask/cl8i0kllo6e8m070e4c4sbr6w_0.png")
image1 = imageio.imread("/root/fish_fillet_image_program_ML/fish/temp/image/cl8i0kllo6e8m070e4c4sbr6w.jpg",pilmode="RGB")
# print(image,type(image))

# show the image
ia.imshow(image)
ia.imshow(image1)

# print(image1.reshape(image1.shape,1))
print(image.shape)
print(image1.shape)
# print(image1[0])

In [4]:

import imageio
import imgaug as ia
from imgaug import augmenters as iaa
import numpy as np
image = imageio.imread("/home/masters/twitterDir/demo/data_aug/images_raw/cl8i0motz1pxq072m4xbs3h7k_0.jpg")
print(image)
u = np.unique(image)
print(u)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 1

/home/masters/anaconda3/envs/hw/lib/python3.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  """


In [ ]:

ia.seed(4)  # 随机值

images = [image]*1
images1 = [image1]*1

seq = iaa.Sequential(
    [iaa.Affine(rotate=(-25, 25)),                  # 旋转区间
     iaa.AdditiveGaussianNoise(scale=(10, 60)),     # 添加高斯白噪声
     iaa.Crop(percent=(0, 0.2)),                    # 实现裁剪，参数为裁剪比例
     iaa.AddToHueAndSaturation((-60, 60)),          # Hue空间调整饱和度
     iaa.Fliplr(0.5),                               # 水平翻转
     iaa.Flipud(0.2),                               # 垂直翻转
     iaa.Resize((0.1,0.1)),
     iaa.Cutout(nb_iterations=(1, 2), size=0.2, squared=True),  # 图像增强之 cutout 生成遮挡块
    #   iaa.ElasticTransformation(alpha=90, sigma=9)  #随机弹性变换（仿射变换的一种）
     ],
    random_order=True)

seq_det = seq.to_deterministic()                    # 每次调用seq_det使得batch的变换相同

images_aug = seq_det(images=images)
images_aug1 = seq_det(images=images1)

print("Augmented:")
# ia.imshow(np.hstack(images_aug))
ia.imshow(ia.draw_grid(images_aug, cols=4, rows=2))
ia.imshow(ia.draw_grid(images_aug1, cols=4, rows=2))


# run


In [5]:
import imageio
import imgaug as ia
from imgaug import augmenters as iaa
import numpy as np

maskisRGB = False



def dealImage(imagename,datapath,savepath):
    image = imageio.imread(f"{datapath}/images_raw/{imagename}.jpg")
    image1 = imageio.imread(f"{datapath}/annotations/{imagename}.png",pilmode="RGB")
    # image1 = image1 // 50
    print(np.unique(image1))
    ia.seed(4)  # 随机值

    images = [image]*5
    images1 = [image1]*5

    seq = iaa.Sequential(
        [
        iaa.Affine(rotate=(-25, 25),order=0,cval=1),                  # 旋转区间
        # iaa.AdditiveGaussianNoise(scale=(10, 60)),     # 添加高斯白噪声
        # iaa.Crop(percent=(0, 0.2)),                    # 实现裁剪，参数为裁剪比例
        # iaa.AddToHueAndSaturation((-60, 60)),          # Hue空间调整饱和度
        iaa.Fliplr(0.5),                               # 水平翻转
        iaa.Flipud(0.4),                               # 垂直翻转
        iaa.Resize({"height": "keep-aspect-ratio", "width": 640},interpolation=0),
        # iaa.Cutout(nb_iterations=(1, 2), size=0.2, squared=True),  # 图像增强之 cutout 生成遮挡块
        #   iaa.ElasticTransformation(alpha=90, sigma=9)  #随机弹性变换（仿射变换的一种）
        ],
        random_order=True)

    seq_det = seq.to_deterministic()                    # 每次调用seq_det使得batch的变换相同

    images_aug = seq_det(images=images)
    images_aug1 = seq_det(images=images1)

    # print(images_aug)

    for i in range(len(images_aug)):
        imageio.imwrite(f"{savepath}/images_raw/{imagename}_{i}.jpg",images_aug[i])
    for i in range(len(images_aug1)):
        print(images_aug1[i].shape)
        if maskisRGB:
            mask = images_aug1[i]
        else:
            mask = images_aug1[i].transpose()[0]
            mask = mask.transpose()
        print(np.unique(mask))
        imageio.imwrite(f"{savepath}/annotations/{imagename}_{i}.png",mask)

    # print("Augmented:")
    # # ia.imshow(np.hstack(images_aug))
    # ia.imshow(ia.draw_grid(images_aug, cols=4, rows=2))
    # ia.imshow(ia.draw_grid(images_aug1, cols=4, rows=2))

In [6]:
import os
fileRoot = os.getcwd()

try:
    os.makedirs("data_aug/annotations")
    os.makedirs("data_aug/images_raw")
except:
    print("exist")

In [7]:


for root, dirs, files in os.walk(f"{fileRoot}/data_raw/images_raw/"):
    # print(root, dirs, files)

    for file in files:
        # print(file[:-4])
        dealImage(file[:-4],f"{fileRoot}/data_raw",f"{fileRoot}/data_aug")
    #     print("file name:",file)
    #     showImg(file)
    break


/home/masters/anaconda3/envs/hw/lib/python3.7/site-packages/ipykernel_launcher.py:11: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  # This is added back by InteractiveShellApp.init_path()
/home/masters/anaconda3/envs/hw/lib/python3.7/site-packages/ipykernel_launcher.py:12: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  if sys.path[0] == '':


[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
(480, 640, 3)
[1 2 3 4 5]
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
(853, 640, 3)
[1 2 3 4 5]
[1 2 3